name: Feature Branch CI

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run lint
      run: |
        pip install flake8
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests with coverage
      run: python -m pytest src/ -v --cov=src --cov-report=term --cov-fail-under=90
      env:
        OPENAI_API_KEY: "test-api-key"
        OPENAI_API_URL: "https://test.openai.com"
        FLASK_ENV: "testing"

    - name: Build application
      run: docker build -t jboard-feature-test .
